### ISSUE TITLE
Some minor notes

### ISSUE THREAD

**Issue by httpdigest** [ElegantWhelp/LWJGL-3-Tutorial#1]
Hi,
nice video tutorials of yours! Keep on doing them.
I just wanted to hint to you the following:

The current code of the method [Camera.getProjection()](https://github.com/ElegantWhelp/LWJGL-3-Tutorial/blob/master/src/render/Camera.java#L25-L29) can be replaced with the following:

``` Java
return projection.translate(position, new Matrix4f());
```

It will lead to fewer multiplications and additions compared to doing Matrix4f.mul(), because Matrix4f.mul() is a pretty expensive operation and the scale/translate/rotate methods are optimized to only do the fewest operations necessary when applying/concatenating/multiplying a matrix transformation to another transformation. :)

Additionally, I would advise everyone to not do any allocations in methods, but instead take a 'target' matrix as "out"-parameter, which results in your getProjection() method to become:

``` Java
public Matrix4f getProjection(Matrix4f dest) {
    return projection.translate(position, dest);
}
```

**Comment by richard-olsen** [comment]
Hello, I'd like to thank you for the feedback. Also, I didn't realize that the translate function also had a destination argument; I'll have to change that after I finish with the world segment. Thank you for the advice :D

**Comment by httpdigest** [comment]
You're welcome.
About the destination parameter: Every method that is a function of `this` (i.e. where the result depends on what `this` was before) has a destination parameter. If you find a method where that's not the case, please tell me. :)
The only methods that don't have a destination parameter are those whose results do not depend on `this`, such as `Matrix4f.translation/rotation/scaling/setOrtho/setPerspective/...` etc., which merely _set_ the matrix to a translation/rotation/scaling or orthographic/perspective projection etc. without combining/concatenating/multiplying it with the previous matrix.
Also, every method that _applies_ (i.e. concatenates/multiplies/combines) a matrix to the previous `this` matrix starts its JavaDoc with "Apply..." and has a paragraph in it that goes like `If M is this matrix and T the ... matrix, then the new matrix will be M * T. ...`
