### ISSUE TITLE
Tiles

### ISSUE THREAD

**Issue by ThoseCoolGamers** [ElegantWhelp/LWJGL-3-Tutorial#3]
When I try to add a new tile by adding a new line of code to the tile class like
	public static Tile tile_3= new Tile("tile_3");
and then use it in the main method like this
	world.setTile(Tile.tile_3,7,6);	
it will put my third tile there but also every other tile becomes tile 3 and don't know why this happens. I've been testing the code and I found that it has to do with the order of the tiles ex:
	public static Tile tile_3= new Tile("tile_3");
	public static Tile tile_2= new Tile("tile_2");
this will make every placed tile in the set tile function tile two but if its this:
	public static Tile tile_2= new Tile("tile_2");
	public static Tile tile_3= new Tile("tile_3");
then every tile in the set tile command will be tile3.
if anyone has a solution to this please help
here is my code:https://github.com/ThoseCoolGamers/some-code

**Comment by richard-olsen** [comment]
Reviewing your code, specifically the Tiles class, I found that you have the tile ID as a static variable. You shouldn't have the ID as a static variable as this will change the ID of the other tiles to the ID of the more recently added tile.

**Comment by ThoseCoolGamers** [comment]
Oh okay thanks that was nice of you! now I can have lots of different tiles
:D
